# This is your new GitHub Actions workflow file
name: Build and Publish Docker Images

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    # This job runs on a fresh Ubuntu virtual machine
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checks out your code from the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Docker Buildx (a modern builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Logs into Docker Hub using the secrets you created
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4. Builds and pushes the CLIENT image
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client   # Path to the client's Dockerfile
          push: true
          tags: |
            yodds/complex-client:latest
            yodds/complex-client:${{ github.sha }}

      # 5. Builds and pushes the SERVER (API) image
      - name: Build and push server (api) image
        uses: docker/build-push-action@v5
        with:
          context: ./server   # Path to the server's Dockerfile
          push: true
          tags: |
            yodds/complex-api:latest
            yodds/complex-api:${{ github.sha }}

      # 6. Builds and pushes the WORKER image
      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker   # Path to the worker's Dockerfile
          push: true
          tags: |
            yodds/complex-worker:latest
            yodds/complex-worker:${{ github.sha }}