name: Build, Test, and Deploy to GKE

on:
  push:
    branches: [ "main" ]

# Make the Git SHA available as a global environment variable
env:
  SHA: ${{ github.sha }}

jobs:
  # ==========================================================
  # Job 1: Build the test image and run tests
  # ==========================================================
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Build test image
        run: docker build -t yodds/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run client tests
        run: docker run -e CI=true yodds/react-test npm test

  # ==========================================================
  # Job 2: Build production images and deploy to GKE
  # ==========================================================
  deploy:
    runs-on: ubuntu-latest
    # This job 'needs' run-tests to succeed before it will start
    needs: run-tests
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- Part 1: Login to Docker Hub (from our previous setup) ---
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # --- Part 2: Authenticate with Google Cloud (This is the new part) ---
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          # This uses the new secret you just created
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      # --- Part 3: Get GKE credentials (Replaces all the gcloud config/get-credentials) ---
      - name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: multi-cluster
          location: us-central1
          project_id: learning-k8s-476313
      
      # --- Part 4: Build and Push Prod Images (from our previous setup) ---
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            yodds/complex-client:latest
            yodds/complex-client:${{ env.SHA }}

      - name: Build and push server (api) image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          push: true
          tags: |
            yodds/complex-api:latest
            yodds/complex-api:${{ env.SHA }}

      - name: Build and push worker image
        uses: docker/build-push-action@v5
        with:
          context: ./worker
          push: true
          tags: |
            yodds/complex-worker:latest
            yodds/complex-worker:${{ env.SHA }}
      
      # --- Part 5: Deploy to GKE (The commands from deploy.sh) ---
      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s
          
          # Force kubernetes to use the new images
          kubectl set image deployments/server-deployment server=yodds/complex-api:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=yodds/complex-worker:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=yodds/complex-client:${{ env.SHA }}